config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
Rails.application.routes.draw do

  default_url_options host: ENV['APP_HOST']
  devise_for :accounts, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  devise_scope :account do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    delete '/logout' => 'devise/sessions#destroy'
    get '/accounts/edit' => 'devise/registrations#edit', as: "edit_account_registration"
    put "/accounts/:id" => "devise/registrations#update", as: "account_registration"
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" } do
    mount Sidekiq::Web => "/sidekiq"
    namespace :admin do
      resources :journals, except: :show do
        resources :journal_accounts, except: :show do
          with_options action: "set_status" do |map|
            map.post '/enable', action: "set_status"
            map.post '/disable', action: "set_status"
          end
        end
      end
      resources :account
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      with_options only: :index do |map|
        map.resources :journals do
          get "/cookies", action: "get_cookies", on: :member
        end
        map.resources :account, controllers: "api/account"
      end
    end
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" || u.role == "ADMIN"} do
    namespace :admin do
      resources :posts do
        with_options on: :member, action: 'change_status' do |map|
          map.post '/publish'
          map.post '/unpublish'
        end
      end
    end
  end

  get '/journal_status' => 'static_pages#journal_status'
  get '/sign_in_status' => 'static_pages#sign_in_status'
  resources :posts, only: [:index, :show]
  root "static_pages#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user ||= user
    if @user.present?
      signed_in_user
    else
      guest_user
    end
  end

  def default_user
    can :journal_status, Journal
  end

  def guest_user
    default_user
  end

  def signed_in_user
    methods = @user.role.downcase
    send(methods)
  end

  def user
    default_user
  end

  def admin
    default_user
    can :manage, Account
    can :manage, Post
  end

  def superadmin
    can :manage, :all
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  ROLE = %w{USER ADMIN SUPERADMIN}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  validates_presence_of :role, :username
  validates_inclusion_of :role, in: ROLE
  validates_uniqueness_of :username, case_sensitive: false
  before_validation :fill_api_key

  def avatar
    md5 = Digest::MD5.new
    md5.update(self.email)
    "http://www.gravatar.com/avatar/#{md5.hexdigest}"
  end



  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  private
  def create_authorization
    authorization = Authorization.new(account_id: self.id)
    authorization.save
  end

  def fill_api_key
    key = generate_api_key SecureRandom.hex(20)
    self.api_key = key
  end

  def generate_api_key key
    matched_key = Account.find_by_api_key(key)
    return key unless matched_key.present?
    generate_api_key SecureRandom.hex(20)
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  include Journalist::JournalModel
end

app/models/journal_account.rb
class JournalAccount < ActiveRecord::Base
  include Journalist::JournalAccountModel

  def toggle_enable
    if enable
      update(enable: false)
    else
      update(enable: true)
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  validates_presence_of :title, :content
  default_scope {order("created_at desc")}

  def update_status
    status = self.published? ? false : true
    self.update(published: status)
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def tag_array
    self.tag_list.split(",")
  end
end

app/models/proxy_authorization.rb
class ProxyAuthorization
  attr_accessor :username, :password
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :exception
  include Api::AuthorizationHelper
  before_action :authorize_account!
  respond_to :json

  rescue_from ActionController::UnknownFormat do
    render json: {msg: "format not yet supported"}.to_json, status: 501
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter do
    @current_ability ||= Ability.new(current_account)
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html {redirect_to root_path, alert: "Kamu tidak memiliki hak akses memasuki halaman"}
      format.json {render json: {msg: "Not Authorize"}.to_json, status: :unauthorized}
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  protected
  def after_sending_reset_password_instructions_path_for(resource_name)
    root_url
    #redirect_to root_url, notice: "We send instruction how to reset password to your email"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :json

  def index
    @presenter = IndexPresenter.new(params)
    respond_with @presenter
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check
  def index
  end

  def journal_status
    @journals = Journal.all
    respond_to do |format|
      format.json
    end
  end

  def sign_in_status
    respond_to do |format|
      format.json
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/api/account_helper.rb
module Api::AccountHelper
end

app/helpers/api/authorization_helper.rb
module Api::AuthorizationHelper
  def headers
    request.headers
  end

  def current_account= account
    @current_account = account
  end

  def current_account
    api_authorization = headers["X-Api-Key"]
    @current_account ||= Account.find_by_api_key(api_authorization)
  end

  def authorized?
    !current_account.nil?
  end

  def authorize_account!
    unless authorized?
      render json: {msg: "Not Authorize"}.to_json, status: :unauthorized
    end
  end

end

app/helpers/api/journals_helper.rb
module Api::JournalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title text
    return "Journalist | #{text}" if text.present?
    return "Journalist"
  end


  def flash_class level
    css_class = {'notice' => "alert alert-info", 'success' => "alert alert-success", 'error' => "alert alert-danger", 'alert' => "alert alert-danger"}
    css_class[level]
  end

  def flash_icon level
    css_class = {'notice' => "fa fa-rocket", 'success' => "fa fa-check", 'error' => "fa fa-times", 'alert' => "fa fa-times"}
    css_class[level]
  end

  def message_status level
    status = {'notice' => "Notice", 'success' => "Success", 'error' => "Error", 'alert' => "Alert"}
    status[level]
  end

  def role_select_helper
    Account::ROLE.map {|role| [role.downcase, role]}
  end

end

app/helpers/journal_accounts_helper.rb
module JournalAccountsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = yield :specific_css
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :specific_js
    = csrf_meta_tags
  %body
    = render "layouts/shared/header"
    #flash
      = render partial: "layouts/shared/flash", locals: {flash: flash}
    #wrapper.container
      = yield
      .row
        .col-md-8
          = yield :content
        .col-md-4
          = yield :side_content

app/views/layouts/shared/_errors.html.haml
- if object.errors.any?
  #error-explenation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li * #{msg}.
  %hr

app/views/layouts/shared/_flash.html.haml
- flash.each do |key, value|
  %div{class: flash_class(key), style: "display: none;"}
    %button.close &times;
    %span{class: flash_icon(key)}
    %strong= "#{message_status(key)} Message"
    %hr.message-inner-separator
    %p= raw(value)

app/views/layouts/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Journalist", root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if can? :read, Journal
          %li= link_to "Journal", admin_journals_path
        - if can? :read, Account
          %li= link_to "Account", admin_account_index_path
        - if can? :manage, Post
          %li= link_to "Post", admin_posts_path
      - unless account_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Forgot Password ?", new_account_password_path
      - if account_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do
              %i.fa.fa-user
              = current_account.full_name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to edit_account_registration_path do
                  %i.fa.fa-user
                  Edit account
              %li
                = link_to logout_path, method: :delete do
                  %i.fa.fa-power-off
                  Log out

app/views/layouts/shared/javascripts/_responder.js.erb
<%= yield :additional_js %>
$("<%= selector %>").modal('hide');
$("<%= selector %>").on('hidden.bs.modal', function(e){
  $(e.target).remove();
  $("#flash").append("<%= j render partial: "layouts/shared/flash", locals: {flash: flash}%>");
  $("#flash .alert").each(function(i, e){
    $(this).delay(i*1000).fadeIn('slow');
  });
});

app/views/layouts/shared/javascripts/_show_modal.js.erb
var modal = $("<%= selector %>");
if (modal.length == 1) {
  modal.modal("hide");
  modal.on('hidden.bs.modal', function(e){
    $(e.target).remove();
    $("body").append("<%= template %>");
    $("<%= selector %>").modal({show: true})
    <%= yield :additional_js %>
  });
}else{
  $("body").append("<%= template %>");
  $("<%= selector %>").modal({show: true})
  <%= yield :additional_js %>
}

app/views/layouts/shared/sidebars/_journal_status.html.haml
- content_for :specific_js do
  = javascript_include_tag 'journal-status', 'data-turbolinks-track' => true
#journal-status{"data-source" => journal_status_url}

app/views/layouts/shared/sidebars/_sign_in.html.haml
%header
  %h3
    %i.fa.fa-user
    Sign in
%hr
%section
  = form_for :account, url: login_path, html: {role: "form", class: "form-horizontal", method: :post} do |f|
    .form-group
      = f.label :login, "Email or Username", class: "sr-only"
      .col-sm-12
        = f.text_field :login, class: "form-control", placeholder: "Email or Username"
    .form-group
      = f.label :password, "Password", class: "sr-only"
      .col-sm-12
        = f.password_field :password, class: "form-control", placeholder: "Password"
    %hr
    .form-group
      .col-sm-6
        %button.btn.btn-primary{type: "submit"}
          %i.fa.fa-sign-in
          Sign in
      .col-sm-6
        %label.checkbox-inline.pull-right
          = f.check_box :remember_me
          Remember me