config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
Rails.application.routes.draw do

  default_url_options host: ENV['APP_HOST']
  devise_for :accounts, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  devise_scope :account do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    delete '/logout' => 'devise/sessions#destroy'
    get '/accounts/edit' => 'devise/registrations#edit', as: "edit_account_registration"
    put "/accounts/:id" => "devise/registrations#update", as: "account_registration"
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" } do
    mount Sidekiq::Web => "/sidekiq"
    namespace :admin do
      resources :journals, except: :show do
        resources :journal_accounts, except: :show do
          with_options action: "set_status" do |map|
            map.post '/enable', action: "set_status"
            map.post '/disable', action: "set_status"
          end
        end
      end
      resources :account
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      with_options only: :index do |map|
        map.resources :journals do
          get "/cookies", action: "get_cookies", on: :member
        end
        map.resources :account, controllers: "api/account"
      end
    end
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" || u.role == "ADMIN"} do
    namespace :admin do
      resources :posts do
        with_options on: :member, action: 'change_status' do |map|
          map.post '/publish'
          map.post '/unpublish'
        end
      end
    end
  end

  get '/journal_status' => 'static_pages#journal_status'
  get '/sign_in_status' => 'static_pages#sign_in_status'
  resources :posts, only: [:index, :show]
  root "static_pages#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  validates_presence_of :title, :content
  default_scope {order("created_at desc")}

  def update_status
    status = self.published? ? false : true
    self.update(published: status)
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def tag_array
    self.tag_list.split(",")
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  # load_and_authorize_resource
  # skip_load_resource :only => [:create]

  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: PostIndexDatatables.new(view_context)}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html {redirect_to admin_post_url(@post), notice: "Record post berhasil dibuat"}
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to admin_post_url(@post), notice: "Record post berhasil diupdate"}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Record post berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  def change_status
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_status
        flash[:success] = "Status post berhasil diupdate"
        format.js
      else
        flash[:error] = "Ermmm, Something went wrong here"
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published, :tag_list)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :json

  def index
    @presenter = IndexPresenter.new(params)
    respond_with @presenter
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
= form_for [:admin, @post], html: {role: "form", class: "form-horizontal"} do |f|
  = render "layouts/shared/errors", object: f.object
  .form-group
    = f.label :title, "Judul", class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, class: "form-control", placeholder: "Judul post"
  .form-group
    = f.label :tag_list, "Tags", class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :tag_list, class: "form-control", placeholder: "Tags"
      %span.help-block Separated by comas (,)
  .form-group
    = f.label :published, "Publish", class: "col-sm-2 control-label"
    .col-sm-10
      .checkbox
        %label
          = f.check_box :published, checked: @post.published
          Publish
  .form-group
    .col-sm-12
      = f.bootsy_area :content, class: "form-control", style: "height: 300px;"
  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      .pull-right
        %button.btn.btn-lg.btn-primary{type: "submit"}
          %i.fa.fa-upload
          Simpan 

app/views/admin/posts/change_status.js.erb
var a = $("#posts").dataTable();
a._fnAjaxUpdate();
$("#flash").append("<%= j render partial: "layouts/shared/flash", locals: {flash: flash}%>");
$("#flash .alert").each(function(i, e){
  $(this).delay(i*1000).fadeIn('slow');
});

app/views/admin/posts/edit.html.haml
= provide(:title, "Tambah Post")
- content_for :specific_js do
  = javascript_include_tag 'post_editor', 'data-turbolinks-track' => true
.row
  .col-md-10
    %h1 Tambah Post
  .col-md-2
%hr
= render 'form'

app/views/admin/posts/index.html.haml
= provide(tittle: "Manage Berita")
- content_for :specific_js do
  = javascript_include_tag 'posts', 'data-turbolinks-track' => true
- content_for :side_content do
  = render "layouts/shared/sidebars/journal_status"

.row
  .col-md-6
    %h1 Manage Berita
  .col-md-6
    .action{style: "margin-top: 20px;"}
      .pull-right
        = link_to new_admin_post_path, class: "btn btn-lg btn-primary" do
          %i.fa.fa-pencil
          Tambah Post
%hr
- content_for :content do
  %table#posts.table.table-bordered{"data-source" => "#{admin_posts_url(format: "json")}"}
    %thead
      %tr
        %th
          .text-center Judul
        %th
          .text-center Tanggal dibuat
        %th
          .text-center Published
        %th
          .text-center Action
    %tbody

app/views/admin/posts/new.html.haml
= provide(:title, "Tambah Post")
- content_for :specific_js do
  = javascript_include_tag 'post_editor', 'data-turbolinks-track' => true
.row
  .col-md-10
    %h1 Tambah Post
  .col-md-2
%hr
= render 'form'

app/views/admin/posts/show.html.haml
= provide(:title, @post.title)
- content_for :side_content do
  = render "layouts/shared/sidebars/journal_status"

.row
  .col-md-10
    %h1= @post.title
  .col-md-2
    - if can? :edit, @post
      .action{style: "margin-top: 20px;"}
        .pull-right
          = link_to edit_admin_post_path(@post), class: "btn btn-lg btn-primary" do
            %i.fa.fa-edit
            Edit
%hr
- content_for :content do
  #post
    #tags
      .row
        .col-md-2
          %p
            %i.fa.fa-tags
              Tags
        .col-md-1
          %p :
        .col-md-9
          %p
            - @post.tag_list.each do |tag|
              %span.label.label-success= tag
    #post-date
      .row
        .col-md-2
          %p
            %i.fa.fa-calendar
              Created at
        .col-md-1
          %p :
        .col-md-9
          %p
            %span.label.label-primary= @post.created_at.to_formatted_s(:long_ordinal)
    %hr
    %article
      = @post.content.html_safe
    %hr