config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
Rails.application.routes.draw do

  default_url_options host: ENV['APP_HOST']
  devise_for :accounts, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  devise_scope :account do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    delete '/logout' => 'devise/sessions#destroy'
    get '/accounts/edit' => 'devise/registrations#edit', as: "edit_account_registration"
    put "/accounts/:id" => "devise/registrations#update", as: "account_registration"
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" } do
    mount Sidekiq::Web => "/sidekiq"
    namespace :admin do
      resources :journals, except: :show do
        resources :journal_accounts, except: :show do
          with_options action: "set_status" do |map|
            map.post '/enable', action: "set_status"
            map.post '/disable', action: "set_status"
          end
        end
      end
      resources :account
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      with_options only: :index do |map|
        map.resources :journals do
          get "/cookies", action: "get_cookies", on: :member
        end
        map.resources :account, controllers: "api/account"
      end
    end
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" || u.role == "ADMIN"} do
    namespace :admin do
      resources :posts do
        with_options on: :member, action: 'change_status' do |map|
          map.post '/publish'
          map.post '/unpublish'
        end
      end
    end
  end

  get '/journal_status' => 'static_pages#journal_status'
  get '/sign_in_status' => 'static_pages#sign_in_status'
  resources :posts, only: [:index, :show]
  root "static_pages#index"
end

app/models/journal_account.rb
class JournalAccount < ActiveRecord::Base
  include Journalist::JournalAccountModel

  def toggle_enable
    if enable
      update(enable: false)
    else
      update(enable: true)
    end
  end
end

app/controllers/admin/journal_accounts_controller.rb
class Admin::JournalAccountsController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: :create
  before_action :set_journal
  before_action :set_journal_account, only: [:show, :edit, :update, :destroy]

  def set_journal
    @journal ||= Journal.find(params[:journal_id])
  end

  def set_journal_account
    @journal_account ||= @journal.journal_accounts.find(params[:id])
  end

  # GET /journal_accounts
  # GET /journal_accounts.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: JournalAccountsIndexDatatables.new(view_context)}
    end
  end

 # GET /journal_accounts/new
  def new
    @journal_account = @journal.journal_accounts.build
    respond_to do |format|
      format.js
    end
  end

  # GET /journal_accounts/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /journal_accounts
  # POST /journal_accounts.json
  def create
    @journal_account = @journal.journal_accounts.build(journal_account_params)
    authorize! :create, @journal_account
    respond_to do |format|
      if @journal_account.save
        flash[:notice] = "Record journal account berhasil dibuat"
        format.js
      else
        format.js {render :new}
      end
    end
  end

  # PATCH/PUT /journal_accounts/1
  # PATCH/PUT /journal_accounts/1.json
  def update
    respond_to do |format|
      if @journal_account.update(journal_account_params)
        flash[:notice] = "Record journal account berhasil diubah"
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /journal_accounts/1
  # DELETE /journal_accounts/1.json
  def destroy
    @journal_account.destroy
    respond_to do |format|
      format.html { redirect_to admin_journal_journal_accounts_url(@journal), notice: 'Record journal account berhasil di hapus' }
      format.json { head :no_content }
    end
  end

  def set_status
    @journal = Journal.find(params[:journal_id])
    @journal_account = @journal.journal_accounts.find(params[:journal_account_id])
    @journal_account.toggle_enable
    respond_to do |format|
      format.js
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_account_params
      params.require(:journal_account).permit(:username, :password, :other)
    end
end

app/helpers/journal_accounts_helper.rb
module JournalAccountsHelper
end

app/views/admin/journal_accounts/_form.html.haml
#journal-account-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "journalAccountModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#journalAccountModalLabel.modal-title
          = @journal_account.new_record? ? "Tambah Jurnal Account" : "Edit Jurnal Account"
      = form_for [:admin, @journal, @journal_account], remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :username, "Username", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :username, class: "form-control", placeholder: "Username bank jurnal"
          .form-group
            = f.label :password, "Password", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :password, class: "form-control", placeholder: "Password bank jurnal"
          .form-group
            = f.label :other, "Lainnya", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :other, class: "form-control", placeholder: "Kode pengaman lainnya pada bank jurnal"
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Simpan
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/journal_accounts/create.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-accounts").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/index.html.haml
= provide(:title, "Manage Journal Account")
- content_for :specific_js do
  = javascript_include_tag 'journal_accounts', 'data-turbolinks-track' => true
- content_for :side_content do
  = render "layouts/shared/sidebars/journal_status"
.row
  .col-md-6
    %h1 Manage Journal Account
  .col-md-6
    .action{style: "margin-top: 20px;"}
      .pull-right
        = link_to admin_journals_path, class: "btn btn-lg btn-default" do
          %i.fa.fa-arrow-left
          Journal
        = link_to new_admin_journal_journal_account_path(@journal), class: "btn btn-lg btn-primary", remote: true do
          %i.fa.fa-pencil
          Tambah Account
%hr/
-content_for :content do
  %table#journal-accounts.table.table-bordered{"data-source" => "#{admin_journal_journal_accounts_url(@journal, format: "json")}"}
    %thead
      %tr
        %th
          .text-center Username
        %th
          .text-center Password
        %th
          .text-center Lainnya
        %th
          .text-center Enabled
        %th
          .text-center Action
    %tbody

app/views/admin/journal_accounts/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-account-modal"} %>

app/views/admin/journal_accounts/set_status.js.erb
var a = $("#journal-accounts").dataTable();
a._fnAjaxUpdate();

app/views/admin/journal_accounts/update.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-accounts").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-account-modal"} %>