config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
Rails.application.routes.draw do

  default_url_options host: ENV['APP_HOST']
  devise_for :accounts, skip: [:sessions, :registrations], controllers: {passwords: "passwords"}
  devise_scope :account do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    delete '/logout' => 'devise/sessions#destroy'
    get '/accounts/edit' => 'devise/registrations#edit', as: "edit_account_registration"
    put "/accounts/:id" => "devise/registrations#update", as: "account_registration"
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" } do
    mount Sidekiq::Web => "/sidekiq"
    namespace :admin do
      resources :journals, except: :show do
        resources :journal_accounts, except: :show do
          with_options action: "set_status" do |map|
            map.post '/enable', action: "set_status"
            map.post '/disable', action: "set_status"
          end
        end
      end
      resources :account
    end
  end

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      with_options only: :index do |map|
        map.resources :journals do
          get "/cookies", action: "get_cookies", on: :member
        end
        map.resources :account, controllers: "api/account"
      end
    end
  end

  authenticate :account, lambda {|u| u.role == "SUPERADMIN" || u.role == "ADMIN"} do
    namespace :admin do
      resources :posts do
        with_options on: :member, action: 'change_status' do |map|
          map.post '/publish'
          map.post '/unpublish'
        end
      end
    end
  end

  get '/journal_status' => 'static_pages#journal_status'
  get '/sign_in_status' => 'static_pages#sign_in_status'
  resources :posts, only: [:index, :show]
  root "static_pages#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
  ROLE = %w{USER ADMIN SUPERADMIN}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  validates_presence_of :role, :username
  validates_inclusion_of :role, in: ROLE
  validates_uniqueness_of :username, case_sensitive: false
  before_validation :fill_api_key

  def avatar
    md5 = Digest::MD5.new
    md5.update(self.email)
    "http://www.gravatar.com/avatar/#{md5.hexdigest}"
  end



  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  private
  def create_authorization
    authorization = Authorization.new(account_id: self.id)
    authorization.save
  end

  def fill_api_key
    key = generate_api_key SecureRandom.hex(20)
    self.api_key = key
  end

  def generate_api_key key
    matched_key = Account.find_by_api_key(key)
    return key unless matched_key.present?
    generate_api_key SecureRandom.hex(20)
  end
end

app/controllers/admin/account_controller.rb
class Admin::AccountController < ApplicationController
  load_and_authorize_resource
  skip_load_resource :only => [:create]
  before_action :set_account, only: [:edit, :update, :destroy]
  before_action :remove_unused_params, only: :update

  def index
    respond_to do |format|
      format.html
      format.json {render json: AccountIndexDatatables.new(view_context)}
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def new
    @account = Account.new
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        flash[:notice] = "Record account berhasil diupdate"
        format.js
      else
        format.js {render :edit}
      end
    end
  end

  def create
    @account = Account.new(account_params)
    authorize! :create, @account
    respond_to do |format|
      if @account.save
        flash[:notice] = "Record account berhasil dibuat"
        format.js
      else
        format.js {render :new}
      end
    end
  end

  def destroy
    @account.destroy
    respond_to do |format|
      format.html {redirect_to admin_account_index_url, notice: "Record account berhasil dihapus"}
      format.json{ head :no_content }
    end
  end

  private
  def set_account
    @account ||= Account.find(params[:id])
  end

  def remove_unused_params
    params[:account].delete(:password) if params[:account][:password].blank?
    params[:account].delete(:password_confirmation) if params[:account][:password_confirmation].blank?
  end

  def account_params
    params.require(:account).permit(:full_name, :role, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/api/account_controller.rb
class Api::AccountController < ApiController
  
  def index
    @account = current_account
    respond_with @account
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/api/account_helper.rb
module Api::AccountHelper
end

app/views/admin/account/_form.html.haml
- url = @account.new_record? ? admin_account_index_path : admin_account_path(@account)
#account-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "accountModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#accountModalLabel.modal-title
          = @account.new_record? ? "Tambah Account" : "Edit Account"
      = form_for @account, url: url, remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :full_name, "Nama Lengkap", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :full_name, class: "form-control", placeholder: "Nama Lengkap", autocomplete: "off"
          .form-group
            = f.label :email, "Email", class: "col-sm-3 control-label"
            .col-sm-9
              = f.email_field :email, class: "form-control", placeholder: "Email", autocomplete: "off"
          .form-group
            = f.label :username, "Username", class: "control-label col-sm-3"
            .col-sm-9
              = f.text_field :username, class: "form-control", placeholder: "Username", autocomplete: "off"
          .form-group
            = f.label :role, "Role", class: "control-label col-sm-3"
            .col-sm-9
              = f.select :role, options_for_select(role_select_helper, selected: @account.role), {}, {class: "form-control"}
          .form-group
            = f.label :password, "Password", class: "control-label col-sm-3"
            .col-sm-9
              = f.password_field :password, class: "form-control", autocomplete: "off", placeholder: "Password"
          .form-group
            = f.label :password_confirmation, "Password Confirmation", class: "control-label col-sm-3"
            .col-sm-9
              = f.password_field :password_confirmation, class: "form-control", autocomplete: "off", placeholder: "Password Confirmation"
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Simpan
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/account/create.js.erb
<% content_for :additional_js do %>
  var a = $("#accounts").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#account-modal"} %>

app/views/admin/account/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#account-modal"} %>

app/views/admin/account/index.html.haml
- provide(:title, "Accounts")
- content_for :specific_js do
  = javascript_include_tag "account", 'data-turbolinks-track' => true
- content_for :side_content do
  = render "layouts/shared/sidebars/journal_status"
.row
  .col-md-6
    %h1 Manage Account
  .col-md-6
    .action{style: "margin-top: 20px;"}
      .pull-right
        = link_to new_admin_account_path, class: "btn btn-lg btn-primary", remote: true do
          %i.fa.fa-pencil
          Tambah Account
%hr
- content_for :content do
  %table#accounts.table.table-bordered{"data-sourse" => "#{admin_account_index_path(format: "json")}"}
    %thead
      %tr
        %th
          .text-center Nama Lengkap
        %th
          .text-center Username
        %th
          .text-center Email
        %th
          .text-center Created at
        %th
          .text-center Action

app/views/admin/account/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#account-modal"} %>

app/views/admin/account/update.js.erb
<% content_for :additional_js do %>
  var a = $("#accounts").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#account-modal"} %>